/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package co.uk.newday;

public class App {

    public static void main(String[] args) {
        String arg0 = args[0];
        Diamond diamond = new Diamond(arg0);
        diamond.print();
    }
}
